package pokemon.maker.fields;

import pokemon.maker.PokemonData;
import pokemon.maker.PokemonDataField;

public enum Move implements PokemonDataField {

	Nothing("0x00", "Nothing"),
	Pound("0x01", "Pound"),
	KarateChop("0x02", "Karate Chop"),
	DoubleSlap("0x03", "Double Slap"),
	CometPunch("0x04", "Comet Punch"),
	MegaPunch("0x05", "Mega Punch"),
	PayDay("0x06", "Pay Day"),
	FirePunch("0x07", "Fire Punch"),
	IcePunch("0x08", "Ice Punch"),
	ThunderPunch("0x09", "Thunder Punch "),
	Gust("0x10", "Gust"),
	WingAttack("0x11", "Wing Attack"),
	Whirlwind("0x12", "Whirlwind"),
	Fly("0x13", "Fly"),
	Bind("0x14", "Bind"),
	Slam("0x15", "Slam"),
	VineWhip("0x16", "Vine Whip"),
	Stomp("0x17", "Stomp"),
	DoubleKick("0x18", "Double Kick"),
	MegaKick("0x19", "Mega KIck"),
	JumpKIck("0x1A", "Jump KIck"),
	RollingKick("0x1B", "RollingKick"),
	SandAttack("0x1C", "Sand Attack"),
	Headbutt("0x1D", "Headbutt"),
	HornAttack("0x1E", "Horn Attack"),
	FuryAttack("0x1F", "Fury Attack"),
	HornDrill("0x20", "Horn Drill"),
	Tackle("0x21", "Tackle"),
	Bodyslam("0x22", "Bodyslam"),
	Wrap("0x23", "Wrap"),
	TakeDown("0x24", "Take Down "),
	Trash("0x25", "Trash"),
	DoubleEdge("0x26", "Double Edge"),
	TailWhip("0x27", "Tail Whip"),
	PoisonSting("0x28", "Poison Sting"),
	TwinNeedle("0x29", "Twin Needle"),
	PinMissle("0x2A", "Pin Missle"),
	Leer("0x2B", "Leer"),
	Bite("0x2C", "Bite"),
	Growl("0x2D", "Growl"),
	Roar("0x2E", "Roar"),
	SuperSonic("0x2F", "SuperSonic"),
	SonicBoom("0x30", "Sonic Boom"),
	Disable("0x32", "Disable"),
	Acid("0x33", "Acid"),
	Ember("0x34", "Ember"),
	FlameThrower("0x35", "FlameThrower"),
	Mist("0x36", "Mist"),
	WaterGun("0x37", "Water Gun"),
	HydroPump("0x38", "Hydro Pump"),
	Surf("0x39", "Surf"),
	IceBeam("0x3A", "Ice Beam"),
	Blizzard("0x3B", "Blizzard"),
	PsyBeam("0x3C", "PsyBeam"),
	BubbleBeam("0x3D", "Bubble Beam"),
	AuroraBeam("0x3E", "Aurora Beam"),
	HyperBeam("0x3F", "Hyper Beam"),
	Peck("0x40", "Peck"),
	DrillPeck("0x41", "Drill Peck"),
	Submission("0x42", "Submission"),
	LowKick("0x43", "Low Kick"),
	Counter("0x44", "Counter"),
	SesmicToss("0x45", "Sesmic Toss"),
	Strength("0x46", "Strength"),
	Absorb("0x47", "Absorb"),
	MegaDrain("0x48", "Mega Drain"),
	LeechSeed("0x49", "Leech Seed"),
	Growth("0x4A", "Growth"),
	RazorWind("0x4B", "Razor Wind"),
	SolarBeam("0x4C", "Solar Beam"),
	PoisonPowder("0x4D", "Poison Powder"),
	StunSpore("0x4E", "Stun Spore"),
	SleepPowder("0x4F", "Sleep Powder"),
	PetalDance("0x50", "Petal Dance"),
	StringShot("0x51", "String Shot"),
	DragonRage("0x52", "Dragon Rage"),
	FireSpin("0x53", "Fire Spin"),
	ThunderShock("0x54", "ThunderShock"),
	ThunderBolt("0x55", "ThunderBolt"),
	ThunderWave("0x56", "ThunderWave"),
	Thunder("0x57", "Thunder"),
	RockThrow("0x58", "Rock Throw"),
	EarthQuake("0x59", "EarthQuake"),
	Fissure("0x5A", "Fissure"),
	Dig("0x5B", "Dig"),
	Toxic("0x5C", "Toxic"),
	Confusion("0x5D", "Confusion"),
	Psychic("0x5E", "Psychic"),
	Hypnosis("0x5F", "Hypnosis"),
	Meditate("0x60", "Meditate"),
	Agility("0x61", "Agility"),
	QuickAttack("0x62", "Quick Attack"),
	Rage("0x63", "Rage"),
	Teleport("0x64", "Teleport"),
	NightShade("0x65", "Night Shade"),
	Mimic("0x66", "Mimic"),
	Screech("0x67", "Screech"),
	DoubleTeam("0x68", "Double Team"),
	Recover("0x69", "Recover"),
	Harden("0x6A", "Harden"),
	Minimized("0x6B", "Minimized"),
	SmokeScreen("0x6C", "Smoke Screen"),
	ConfuseRay("0x6D", "Confuse Ray"),
	WithDraw("0x6E", "WithDraw"),
	DefenceCurl("0x6F", "Defence Curl"),
	Barrier("0x70", "Barrier"),
	Lightscreen("0x71", "Light screen"),
	Haze("0x72", "Haze"),
	Reflect("0x73", "Reflect"),
	Focus("0x74", "Focus"),
	Bide("0x75", "Bide"),
	Metronome("0x76", "Metronome"),
	MirrorMove("0x77", "Mirror Move"),
	SelfDestruct("0x78", "Self Destruct"),
	EggBomb("0x79", "Egg Bomb"),
	Lick("0x7A", "Lick"),
	Smog("0x7B", "Smog"),
	Sludge("0x7C", "Sludge"),
	BoneClub("0x7D", "Bone Club"),
	FireBlast("0x7E", "Fire Blast"),
	Waterfall("0x7F", "Waterfall"),
	Clamp("0x80", "Clamp"),
	Swift("0x81", "Swift"),
	SkullBash("0x82", "Skull Bash"),
	SpikeCannon("0x83", "Spike Cannon"),
	Constrict("0x84", "Constrict"),
	Amnesia("0x85", "Amnesia"),
	Kinesis("0x86", "Kinesis"),
	Softboiled("0x87", "Softboiled"),
	HiJumpKick("0x88", "Hi-Jump Kick"),
	Glare("0x89", "Glare"),
	DreamEater("0x8A", "Dream Eater"),
	PoisonGas("0x8B", "Poison Gas"),
	Barrage("0x8C", "Barrage"),
	LeechLife("0x8D", "Leech Life"),
	LovelyKiss("0x8E", "Lovely Kiss"),
	SkyAttack("0x8F", "Sky Attack"),
	Transform("0x90", "Transform"),
	Bubble("0x91", "Bubble"),
	DizzyPunch("0x92", "Dizzy Punch"),
	Spore("0x93", "Spore"),
	Flash("0x94", "Flash"),
	Psywave("0x95", "Psywave"),
	Splash("0x96", "Splash"),
	AcidArmor("0x97", "Acid Armor"),
	Crabhammer("0x98", "Crabhammer"),
	Explosion("0x99", "Explosion"),
	FurySwipe("0x9A", "Fury Swipe"),
	Bonemerang("0x9B", "Bonemerang"),
	Rest("0x9C", "Rest"),
	RockSlide("0x9D", "Rock Slide"),
	HyperFang("0x9E", "Hyper Fang"),
	Sharpen("0x9F", "Sharpen"),
	Conversion("0xA0", "Conversion"),
	TriAttack("0xA1", "Tri Attack"),
	SuperFang("0xA2", "Super Fang"),
	Slash("0xA3", "Slash"),
	Substitute("0xA4", "Substitute"),
	Struggle("0xA5", "Struggle");
	
	private final String hexCode;
	private final String name;
	private Move(final String hexCode, final String name) {
		this.hexCode = hexCode;
		this.name = name;
	}
	
	public String[] getHex() {
		return PokemonData.hex(this.hexCode);
	}
	
	public String getName() {
		return this.name;
	}
}
