package pokemon.maker.fields;

import pokemon.maker.PokemonData;
import pokemon.maker.PokemonDataField;

public enum Species implements PokemonDataField {
	Rhydon("0x01", "Rhydon"),
	Kangaskhan("0x02", "Kangaskhan"),
	NidoranM("0x03", "Nidoran♂"),
	Clefairy("0x04", "Clefairy"),
	Spearow("0x05", "Spearow"),
	Voltorb("0x06", "Voltorb"),
	Nidoking("0x07", "Nidoking"),
	Slowbro("0x08", "Slowbro"),
	Ivysaur("0x09", "Ivysaur"),
	Exeggutor("0x0A", "Exeggutor"),
	Lickitung("0x0B", "Lickitung"),
	Exeggcute("0x0C", "Exeggcute"),
	Grimer("0x0D", "Grimer"),
	Gengar("0x0E", "Gengar"),
	NidoranF("0x0F", "Nidoran♀"),
	Nidoqueen("0x10", "Nidoqueen"),
	Cubone("0x11", "Cubone"),
	Rhyhorn("0x12", "Rhyhorn"),
	Lapras("0x13", "Lapras"),
	Arcanine("0x14", "Arcanine"),
	Mew("0x15", "Mew"),
	Gyarados("0x16", "Gyarados"),
	Shellder("0x17", "Shellder"),
	Tentacool("0x18", "Tentacool"),
	Gastly("0x19", "Gastly"),
	Scyther("0x1A", "Scyther"),
	Staryu("0x1B", "Staryu"),
	Blastoise("0x1C", "Blastoise"),
	Pinsir("0x1D", "Pinsir"),
	Tangela("0x1E", "Tangela"),
	Growlithe("0x21", "Growlithe"),
	Onix("0x22", "Onix"),
	Fearow("0x23", "Fearow"),
	Pidgey("0x24", "Pidgey"),
	Slowpoke("0x25", "Slowpoke"),
	Kadabra("0x26", "Kadabra"),
	Graveler("0x27", "Graveler"),
	Chansey("0x28", "Chansey"),
	Machoke("0x29", "Machoke"),
	MrMime("0x2A", "Mr. Mime"),
	Hitmonlee("0x2B", "Hitmonlee"),
	Hitmonchan("0x2C", "Hitmonchan"),
	Arbok("0x2D", "Arbok"),
	Parasect("0x2E", "Parasect"),
	Psyduck("0x2F", "Psyduck"),
	Drowzee("0x30", "Drowzee"),
	Golem("0x31", "Golem"),
	Magmar("0x33", "Magmar"),
	Electabuzz("0x35", "Electabuzz"),
	Magneton("0x36", "Magneton"),
	Koffing("0x37", "Koffing"),
	Mankey("0x39", "Mankey"),
	Seel("0x3A", "Seel"),
	Diglett("0x3B", "Diglett"),
	Tauros("0x3C", "Tauros"),
	Farfetchd("0x40", "Farfetch'd"),
	Venonat("0x41", "Venonat"),
	Dragonite("0x42", "Dragonite"),
	Doduo("0x46", "Doduo"),
	Poliwag("0x47", "Poliwag"),
	Jynx("0x48", "Jynx"),
	Moltres("0x49", "Moltres"),
	Articuno("0x4A", "Articuno"),
	Zapdos("0x4B", "Zapdos"),
	Ditto("0x4C", "Ditto"),
	Meowth("0x4D", "Meowth"),
	Krabby("0x4E", "Krabby"),
	Vulpix("0x52", "Vulpix"),
	Ninetales("0x53", "Ninetales"),
	Pikachu("0x54", "Pikachu"),
	Raichu("0x55", "Raichu"),
	Dratini("0x58", "Dratini"),
	Dragonair("0x59", "Dragonair"),
	Kabuto("0x5A", "Kabuto"),
	Kabutops("0x5B", "Kabutops"),
	Horsea("0x5C", "Horsea"),
	Seadra("0x5D", "Seadra"),
	Sandshrew("0x60", "Sandshrew"),
	Sandslash("0x61", "Sandslash"),
	Omanyte("0x62", "Omanyte"),
	Omastar("0x63", "Omastar"),
	Jigglypuff("0x64", "Jigglypuff"),
	Wigglytuff("0x65", "Wigglytuff"),
	Eevee("0x66", "Eevee"),
	Flareon("0x67", "Flareon"),
	Jolteon("0x68", "Jolteon"),
	Vaporeon("0x69", "Vaporeon"),
	Machop("0x6A", "Machop"),
	Zubat("0x6B", "Zubat"),
	Ekans("0x6C", "Ekans"),
	Paras("0x6D", "Paras"),
	Poliwhirl("0x6E", "Poliwhirl"),
	Poliwrath("0x6F", "Poliwrath"),
	Weedle("0x70", "Weedle"),
	Kakuna("0x71", "Kakuna"),
	Beedrill("0x72", "Beedrill"),
	Dodrio("0x74", "Dodrio"),
	Primeape("0x75", "Primeape"),
	Dugtrio("0x76", "Dugtrio"),
	Venomoth("0x77", "Venomoth"),
	Dewgong("0x78", "Dewgong"),
	Caterpie("0x7B", "Caterpie"),
	Metapod("0x7C", "Metapod"),
	Butterfree("0x7D", "Butterfree"),
	Machamp("0x7E", "Machamp"),
	Golduck("0x80", "Golduck"),
	Hypno("0x81", "Hypno"),
	Golbat("0x82", "Golbat"),
	Mewtwo("0x83", "Mewtwo"),
	Snorlax("0x84", "Snorlax"),
	Magikarp("0x85", "Magikarp"),
	Muk("0x88", "Muk"),
	Kingler("0x8A", "Kingler"),
	Cloyster("0x8B", "Cloyster"),
	Electrode("0x8D", "Electrode"),
	Clefable("0x8E", "Clefable"),
	Weezing("0x8F", "Weezing"),
	Persian("0x90", "Persian"),
	Marowak("0x91", "Marowak"),
	Haunter("0x93", "Haunter"),
	Abra("0x94", "Abra"),
	Alakazam("0x95", "Alakazam"),
	Pidgeotto("0x96", "Pidgeotto"),
	Pidgeot("0x97", "Pidgeot"),
	Starmie("0x98", "Starmie"),
	Bulbasaur("0x99", "Bulbasaur"),
	Venusaur("0x9A", "Venusaur"),
	Tentacruel("0x9B", "Tentacruel"),
	Goldeen("0x9D", "Goldeen"),
	Seaking("0x9E", "Seaking"),
	Ponyta("0xA3", "Ponyta"),
	Rapidash("0xA4", "Rapidash"),
	Rattata("0xA5", "Rattata"),
	Raticate("0xA6", "Raticate"),
	Nidorino("0xA7", "Nidorino"),
	Nidorina("0xA8", "Nidorina"),
	Geodude("0xA9", "Geodude"),
	Porygon("0xAA", "Porygon"),
	Aerodactyl("0xAB", "Aerodactyl"),
	Magnemite("0xAD", "Magnemite"),
	Charmander("0xB0", "Charmander"),
	Squirtle("0xB1", "Squirtle"),
	Charmeleon("0xB2", "Charmeleon"),
	Wartortle("0xB3", "Wartortle"),
	Charizard("0xB4", "Charizard"),
	Oddish("0xB9", "Oddish"),
	Gloom("0xBA", "Gloom"),
	Vileplume("0xBB", "Vileplume"),
	Bellsprout("0xBC", "Bellsprout"),
	Weepinbell("0xBD", "Weepinbell"),
	Victreebel("0xBE", "Victreebel");
	
	private final String hexCode;
	private final String name;
	private Species(final String hexCode, final String name) {
		this.hexCode = hexCode;
		this.name = name;
	}
	
	public String[] getHex() {
		return PokemonData.hex(this.hexCode);
	}
	
	public String getName() {
		return this.name;
	}
}
